#!/usr/bin/env python
import os
import sys
app_path = os.getenv('PYOSSIM_DIR')
sys.path.append(app_path)

from apps.ossimImageCompare import pyossimImageCompare

#can also go into utils
#should this be autogenerated ??
class PyOssimApp:
    def __init__(self, name, args):
        self.name = name
        self.argc = len(args)
        self.argv = args
        self.tfile = getTemplateFile()

    def run(self):
        init = ossimInit.instance()
        init.initialize()    
        if self.name == 'ossim-image-compare':
            print "Running ossim-image-compare with arguments (" + self.argv + ")"
            ret = pyossimImageCompare(self.argc,self.argv)
            if ret != 0:
                print "OSSIM application " + self.name + " failed with arguments (" + self.argv + ")"
#        afile = generate()
        else:
            print "no python wrappers found for: '" + self.name + "'" 
        #RunAppThread for now run as python threads (do we need this?)
        #alternative run from lib pyossim (seems better)
        #runThread(afile, self.args)
                
#    def generate(self):
#        
#        fname = ossimapp + self.name + ".py"
#        f = open(fname)
#        f.write(
#        
#        import pyossim.apps.$self.name
#        $self.name.run(args)
#        
#        
#        )
#        f.close()
#        
#        
#        
#        return fname
#    

        
